"""init

Revision ID: bf2e46d80385
Revises: 
Create Date: 2026-08-01 16:16:12.558595
"""
from alembic import op
import sqlalchemy as sa


revision = 'bf2e46d80385'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('picture_url', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('email_threads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('gmail_thread_id', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=998), nullable=False),
    sa.Column('thread_summary', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_threads_gmail_thread_id'), 'email_threads', ['gmail_thread_id'], unique=False)
    op.create_index(op.f('ix_email_threads_user_id'), 'email_threads', ['user_id'], unique=False)
    op.create_table('gmail_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('google_sub', sa.String(length=255), nullable=False),
    sa.Column('access_token', sa.String(length=2048), nullable=False),
    sa.Column('refresh_token', sa.String(length=2048), nullable=False),
    sa.Column('token_expiry', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scopes', sa.String(length=1024), nullable=False),
    sa.Column('history_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_sub'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('writing_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tone', sa.String(length=50), nullable=False),
    sa.Column('signature', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('email_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('gmail_message_id', sa.String(length=255), nullable=False),
    sa.Column('sender', sa.String(length=998), nullable=False),
    sa.Column('sender_domain', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=998), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ai_summary_short', sa.Text(), nullable=True),
    sa.Column('ai_summary_detailed', sa.Text(), nullable=True),
    sa.Column('ai_summary_bullets', sa.Text(), nullable=True),
    sa.Column('priority', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='priority'), nullable=True),
    sa.Column('priority_reason', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('IMPORTANT', 'REQUIRES_ACTION', 'INFORMATIONAL', 'NEWSLETTER_MARKETING', 'LOW_VALUE', name='emailcategory'), nullable=True),
    sa.Column('importance_score', sa.Integer(), nullable=True),
    sa.Column('importance_positive_signals', sa.Text(), nullable=True),
    sa.Column('importance_negative_signals', sa.Text(), nullable=True),
    sa.Column('is_phishing_suspected', sa.Boolean(), nullable=False),
    sa.Column('phishing_reason', sa.Text(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['email_threads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gmail_message_id')
    )
    op.create_index(op.f('ix_email_messages_category'), 'email_messages', ['category'], unique=False)
    op.create_index(op.f('ix_email_messages_importance_score'), 'email_messages', ['importance_score'], unique=False)
    op.create_index(op.f('ix_email_messages_is_phishing_suspected'), 'email_messages', ['is_phishing_suspected'], unique=False)
    op.create_index(op.f('ix_email_messages_priority'), 'email_messages', ['priority'], unique=False)
    op.create_index(op.f('ix_email_messages_sender_domain'), 'email_messages', ['sender_domain'], unique=False)
    op.create_index(op.f('ix_email_messages_thread_id'), 'email_messages', ['thread_id'], unique=False)
    op.create_index(op.f('ix_email_messages_user_id'), 'email_messages', ['user_id'], unique=False)
    op.create_table('follow_ups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('remind_after_days', sa.Integer(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('suggested_draft', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['email_threads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_follow_ups_user_id'), 'follow_ups', ['user_id'], unique=False)
    op.create_table('action_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email_message_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['email_message_id'], ['email_messages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_items_user_id'), 'action_items', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_action_items_user_id'), table_name='action_items')
    op.drop_table('action_items')
    op.drop_index(op.f('ix_follow_ups_user_id'), table_name='follow_ups')
    op.drop_table('follow_ups')
    op.drop_index(op.f('ix_email_messages_user_id'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_thread_id'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_sender_domain'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_priority'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_is_phishing_suspected'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_importance_score'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_category'), table_name='email_messages')
    op.drop_table('email_messages')
    op.drop_table('writing_preferences')
    op.drop_table('gmail_accounts')
    op.drop_index(op.f('ix_email_threads_user_id'), table_name='email_threads')
    op.drop_index(op.f('ix_email_threads_gmail_thread_id'), table_name='email_threads')
    op.drop_table('email_threads')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
